### ISSUE TITLE
[op-acceptor]: Support alerting config in test/package configuration

### ISSUE THREAD

**Issue by teddyknox** [ethereum-optimism/infra#275]
With NAT tests taking too long to run in pre-merge CI, and with NAT testing being inherently less deterministic than, say, action tests, it will likely be a common problem that tests that succeed during development do not always success in post-merge CI. That is, flaky tests will be a reality. Flaky tests are problematic for obvious reasons; if they are not fixed quickly they can mask other issues and seed a kind of complacency that defeats the purpose of long-running post-merge CI tests.

Currently, the op-acceptor CI job in the ethereum-optimism/optimism monorepo is configured to alert a single user group in the event of a failed run. This is better than no alerting, but unless the alerted user group includes all engineers (noisy), someone within the alerted group still needs to take the extra step of notifying the engineer that owns that particular test of the failure, a responsibility that often falls between the cracks.

An improvement on this would be a system where engineers could register themselves as the owner of a NAT test, so that if that test failed in post-merge CI for any reason, they would be alerted directly, and could fix the problem immediately.

The simplest solution to this would be to update the configuration schema accepted by op-acceptor to also support an `owners` field on a per test/package level, like so:

```yaml
gates:
  - id: base
    description: "Sanity/smoke acceptance tests for all networks."
    tests:
      - name: TestChainFork
        package: github.com/ethereum-optimism/optimism/op-acceptance-tests/tests/base/...
        owners:
          -  teddyknox
```

There are a few complications to consider with this design however. Let's say there's a package level test declaration like the above, and an engineer adds a test to the package that they would like to own (without owning the rest of the tests in the package). How should they update the configuration without suddenly needing to enumerate every single test + subpackage in the package, and explicitly assign its ownership? I can imagine a few different solutions, all requiring larger changes to the test configuration schema than just adding an `owners` field.
