### ISSUE TITLE
Support env var config in op-acceptor

### ISSUE THREAD

**Issue by teddyknox** [ethereum-optimism/infra#355]
Supporting env vars config within test configuration would enable test frameworks with dynamic options configurable with env vars to be properly configured for tests run with op-acceptor. For example, the devstack/devnet-sdk which can be configured to run tests against sysgo or kurtosis/netchef based on `DEVSTACK_ORCHESTRATOR={sysgo,sysext}`. Right now this is configured externally to op-acceptor which does not allow a single test to be run with different env var configurations within a single run of op-acceptor.

e.g. in a gate config

```
  - id: interop
    inherits:
      - base
    description: "Interop network tests."
    tests:
      - package: github.com/ethereum-optimism/optimism/op-acceptance-tests/tests/interop
        env:
            DEVSTACK_ORCHESTRATOR: sysext
```
